apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-ceph-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: axlab-ceph-cluster-cephfs_k8s-test-volume
    volumeAttributes:
      clusterID: axlab-ceph-cluster
      fsName: cephfs_k8s
      pool: cephfs_k8s_data
    nodeStageSecretRef:
      name: csi-cephfs-secret-manual
      namespace: kube-system