apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: proxmox-cephfs
  #storageClassName: "" # IMPORTANTE: vacío para que se enlace al PV manual
  #volumeName: test-ceph-pv # Se enlaza directamente a tu PV
  resources:
    requests:
      storage: 1Gi
