apiVersion: v1
kind: Pod
metadata:
  name: test-multus-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: ceph-storage-net
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "ip addr show; sleep 3600"]